    version: '3.9'
    services:
      pg_db:
        image: postgres:16
        environment:
          POSTGRES_USER: leandro
          POSTGRES_PASSWORD: luizalabs
          POSTGRES_DB: favorite_products_db
        ports:
          - "5432:5432"
        healthcheck:
          test: "pg_isready -U postgres -h 127.0.0.1 -d postgres"
          interval: 30s
          timeout: 10s
          retries: 3

      app:
        build: .
        ports:
          - "3000:3000"
        env_file:
        - .env
        depends_on:
          pg_db:
            condition: service_healthy
        # restart: always